name: Promo Scraping Intermarche

# Controls when the action will run.
on:
  #push:
  #  branches: main
  schedule:
    - cron: '15/15 13-14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
        
      - name: Check if latest line in file matches today's date
        id: check_date
        run: |
          # Get today's date in YYYYMMDD format
          today_date=$(date +'%Y%m%d')
  
          # Read the latest line from the file
          if [ -f log/last_execution.txt ]; then
            latest_line=$(tail -n 1 log/last_execution.txt)
            echo "Latest line in file: $latest_line"
  
            # Compare the latest line with today's date
            if [ "$latest_line" == "$today_date" ]; then
              echo "file_has_today_date=true" >> $GITHUB_ENV
              echo "::set-output name=file_has_today_date::true"
            else
              echo "file_has_today_date=false" >> $GITHUB_ENV
              echo "::set-output name=file_has_today_date::false"
            fi
          else
            echo "File does not exist."
            echo "file_has_today_date=false" >> $GITHUB_ENV
            echo "::set-output name=file_has_today_date::false"
          fi

      - name: Run actions if file doesn't have today's date
        if: steps.check_date.outputs.file_has_today_date == 'false'
        run: echo "The latest line in the file matches today's date. Running subsequent actions."
        
      - name: setup python
        if: steps.check_date.outputs.file_has_today_date == 'false'
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.15' # install the python version needed
          
      - name: install python packages
        if: steps.check_date.outputs.file_has_today_date == 'false'
        run: |
            python -m pip install --upgrade pip
            pip install requests pandas ua_generator
                    
      - name: execute py script 
        if: steps.check_date.outputs.file_has_today_date == 'false'
        run: python scrape_intermarche.py
            
      - name: commit files
        if: steps.check_date.outputs.file_has_today_date == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m 'update'
            
      - name: push changes
        if: steps.check_date.outputs.file_has_today_date == 'false'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
